- name: Build Jira Container
  docker_container:
    name: Jira
    image: atlassian/jira-software
    recreate: yes
    state: started
    published_ports: "{{ jira_port }}:{{ jira_port }}"
    volumes:
      - "{{ vol_dir }}/jira/:{{ home_dir }}/jira/"

- name: Move JDBC Drive to the proper place
  command: docker exec Jira bash -c "cp {{ home_dir }}/jira/mysql-connector-java-5.1.48.jar {{ jira_driver_dir }}"

- name: Restart after the driver is in the proper spot
  docker_container:
    name: Jira
    restart: yes