- name: Build Jira Container
  docker_container:
    name: Jira
    image: atlassian/jira-software
    recreate: yes
    state: started
    published_ports: "{{ jira_port }}:{{ jira_port }}"
    volumes:
      - "{{ vol_dir }}/jira/:{{ home_dir }}/jira/"

# TODO: This stems from an issue from mysql role, fix and remove this
- name: Fix wierd permissions issue with connector file
  command: docker exec Jira bash -c "chmod 777 {{ home_dir }}/jira/{{ mysql_jira_jar }}"


- name: Move JDBC Drive to the proper place
  command: docker exec Jira bash -c "cp {{ home_dir }}/jira/{{ mysql_jira_jar }} {{ jira_driver_dir }}"

- name: Restart after the driver is in the proper spot
  docker_container:
    name: Jira
    restart: yes