- name: Create Bitbucket Container
  docker_container:
    name: Bitbucket
    image: atlassian/bitbucket-server
    published_ports: "{{ bitbucket_ip }}:80:{{ bitbucket_port }}"
    state: started
    recreate: yes
    volumes:
      - "{{ vol_dir }}/bitbucket/:{{ home_dir }}/bitbucket"

- name: Move JDBC Drive to the proper place
  command: docker exec Bitbucket bash -c "cp {{ home_dir }}/bitbucket/{{ mysql_bin_jar }} {{ home_dir }}/bitbucket/lib/"
  when: 'mysql|bool'

- name: Restart after the driver is in the proper spot
  docker_container:
    name: Bitbucket
    restart: yes