- name: Create Bitbucket Container
  docker_container:
    name: Bitbucket
    image: atlassian/bitbucket-server
    published_ports: "{{ bitbucket_port }}:{{ bitbucket_port }}"
    state: started
    volumes:
      - "{{ vol_dir }}/bitbucket:/data"