- name: Create Confluence Container
  docker_container:
    name: Confluence
    image: atlassian/confluence-server
    published_ports: "{{ confluence_port }}:{{ confluence_port }}"
    state: started
    recreate: yes
    volumes:
      - "{{ vol_dir }}/confluence/:{{ home_dir }}/confluence/"

- name: Move JDBC Drive to the proper place
  command: docker exec Confluence bash -c "cp {{ home_dir }}/confluence/{{ mysql_bin_jar }} {{ confluence_driver_dir }}"

- name: Restart after the driver is in the proper spot
  docker_container:
    name: Confluence
    restart: yes