- name: Create Crowd Container
  docker_container:
    name: Crowd
    image: atlassian/crowd
    published_ports: "{{ crowd_port }}:{{ crowd_port }}"
    state: started
    volumes:
      - "{{ vol_dir }}/crowd:/data"