---
- name: Server Setup
  hosts: atlassian
  gather_facts: yes
  tasks:
  - name: Set up Daily Cron job
    cron: 
      name: Set up Daily Backup Job to run at 2 a.m.
      hour: 2
      job: "ansible-playbook {{ backup_script }} --extra-vars \"location=daily\""
  - name: Set up Weekly Cron jobs
    cron: 
      name: Set up Weekly Backup Job to run at 3 a.m on Sunday.
      weekday: 0 
      hour: 3
      job: "ansible-playbook {{ backup_script }} --extra-vars \"location=weekly\""
  - name: Set up Monthly Cron jobs
    cron: 
      name: Set up Monthly Backup Job to run at 2.
      day: 1 
      hour: 4
      job: "ansible-playbook {{ backup_script }} --extra-vars \"location=monthly\""  