- name: Create Bamboo Container
  docker_container:
    name: Bamboo
    image: atlassian/bamboo-server
    published_ports: "{{ bamboo_port }}:{{ bamboo_port }}"
    state: started
    volumes:
      - "{{ vol_dir }}/bamboo:/data"