- name: Create MySQL Container
  docker_container:
    name: MySQL
    image: mysql:5.7
    published_ports: "{{ mysql_port }}:{{ mysql_port }}"
    state: started
    recreate: yes
    volumes:
      - "{{ vol_dir }}/mysql:/var/lib/mysql"
      - "{{ vol_dir }}/mysql-conf:/etc/mysql/conf.d/"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_password }}"

- name: Wait for mysql service to start before creating databases
  wait_for: 
    host: "{{ mysql_ip }}"
    port: "{{ mysql_port }}"
    delay: 5
    timeout: 60

- name: Make "{{ make_db }}"
  mysql_db:
    login_user: root
    login_password: "{{ mysql_password }}"
    login_host: "{{ mysql_ip }}"
    login_port: "{{ mysql_port }}"
    name: "{{ make_db }}"
    state: present
  loop:
    - jira_db
    - confluence_db
    - bamboo_db
    - crowd_db
    - stash_db
    - bitbucket_db
  loop_control:
    loop_var: make_db

# - name: Make Bitbucket
#   mysql_db:
#     name: bitbucket_db
#     login_user: root
#     login_password: "{{ mysql_password }}"
#     login_host: "{{ mysql_ip }}"
#     login_port: "{{ mysql_port }}"
#     state: present
#     config_file: /etc/mysql/conf.d/bitbucket.cnf

- name: Create db_user and give privileges
  mysql_user:
    login_user: root
    login_password: "{{ mysql_password }}"
    login_host: "{{ mysql_ip }}"
    login_port: "{{ mysql_port }}"
    host: 172.17.0.1
    name: db_user
    password: "{{ mysql_password }}"
    state: present
    priv: '*.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,REFERENCES,ALTER,INDEX,CREATE TEMPORARY TABLES'
