---
- name: Atlassian Tool Setup
  hosts: atlassian
  gather_facts: yes
  tasks: 
  - name: Pull in variables from group_vars/vars
    include_vars: group_vars/vars
    
  - name: Download Dependencies
    apt:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    loop:
      - docker
      - python3-pip
    loop_control:
      loop_var: packages
  - name: Install docker-py
    pip:
      name: docker-py
  - name: Start Docker 
    service: 
      name: docker
      state: started
  - name: Pull Atlassian images
    docker_image:
      name: "{{ docker_images }}"
      source: pull
    loop:
      - mysql
      - atlassian/jira-software
      - atlassian/confluence-server
      - atlassian/bamboo-server
      - atlassian/bitbucket-server
      - atlassian/crowd
      - atlassian/stash
    loop_control:
      loop_var: docker_images
  - name: Create Containers
    include: "{{ containers }}"
    loop: 
      - roles/mysql/main.yml
      - roles/jira/main.yml
      - roles/confluence/main.yml
      - roles/bamboo/main.yml
      - roles/bitbucket/main.yml
      - roles/crowd/main.yml
    loop_control:
      loop_var: containers