---
- name: Atlassian Tool Setup
  hosts: atlassian
  gather_facts: yes
  tasks: 
  - name: Pull in variables from group_vars/vars
    include_vars: "{{ variable_file }}"
    loop: 
      - group_vars/vars
      - group_vars/vault
    loop_control:
      loop_var: variable_file

  - name: Create volume directories if they do not exist
    file:
      path: "{{ vol_dir }}/{{ tool_dir }}"
      state: directory
    loop:
      - bitbucket
      - crowd
      - jira
      - confluence
      - bamboo
      - mysql
    loop_control:
      loop_var: tool_dir
    
  - name: Make sure MySQL connector bin is in each volume (except jira)
    copy: 
      src: "{{ vol_dir }}/{{ mysql_bin_jar }}"
      dest: "{{ vol_dir }}/{{ vol }}/{{ mysql_bin_jar }}"
    loop:
      - bamboo
      - confluence
      - bitbucket
      - crowd
    loop_control:
      loop_var: vol
    when: 'mysql|bool'

  - name: Move jira connector to it's volume
    copy:
      src: "{{ vol_dir }}/{{ mysql_jira_jar }}"
      dest: "{{ vol_dir }}/jira/{{ mysql_jira_jar }}"
    when: 'mysql|bool'

  - name: Start Docker 
    service: 
      name: docker
      state: started

  - name: Create Containers
    include: "{{ containers }}"
    loop: "{{ list_of_roles }}"
    loop_control:
      loop_var: containers
