---
- name: Atlassian Tool Setup
  hosts: atlassian
  gather_facts: yes
  tasks: 
  - name: Pull in variables from group_vars/vars
    include_vars: "{{ variable_file }}"
    loop: 
      - group_vars/vars
      - group_vars/vault
    loop_control:
      loop_var: variable_file    
  
  - name: Download Dependencies
    apt:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    loop:
      - docker
      - python3-pip
    loop_control:
      loop_var: packages

  - name: Install docker-py
    pip:
      name: docker-py
  
  - name: Copy host file to Ansible Default Location
    copy:
      src: /root/Ansible/Atlassian/hosts
      dest: /etc/ansible/hosts
    
  - name: Create volume directories if they do not exist
    file:
      path: "{{ vol_dir }}/{{ tool_dir }}"
      state: directory
      mode: '0777'
    loop:
      - bitbucket
      - crowd
      - jira
      - confluence
      - bamboo
      - mysql
    loop_control:
      loop_var: tool_dir
    
  - name: Make sure MySQL connector bin is in each volume (except jira)
    copy: 
      src: "{{ vol_dir }}/{{ mysql_bin_jar }}"
      dest: "{{ vol_dir }}/{{ vol }}/{{ mysql_bin_jar }}"
    loop:
      - bamboo
      - confluence
      - bitbucket
      - crowd
    loop_control:
      loop_var: vol

  - name: Move jira connector to it's volume
    copy:
      src: "{{ vol_dir }}/{{ mysql_jira_jar }}"
      dest: "{{ vol_dir }}/jira/{{ mysql_jira_jar }}"

  - name: Start Docker 
    service: 
      name: docker
      state: started
  - name: Pull Atlassian images
    docker_image:
      name: "{{ docker_images }}"
      source: pull
    loop:
      - mysql
      - atlassian/jira-software
      - atlassian/confluence-server
      - atlassian/bamboo-server
      - atlassian/bitbucket-server
      - atlassian/crowd
    loop_control:
      loop_var: docker_images
  - name: Create Containers
    include: "{{ containers }}"
    loop: 
      - roles/mysql/main.yml
      - roles/jira/main.yml
      - roles/confluence/main.yml
      - roles/bamboo/main.yml
      - roles/bitbucket/main.yml
      - roles/crowd/main.yml
    loop_control:
      loop_var: containers