---
- name: Atlassian Tool Setup
  hosts: atlassian
  gather_facts: yes
  tasks: 
  - name: Pull in variables from group_vars/vars
    include_vars: "{{ variable_file }}"
    loop: 
      - group_vars/vars
      - group_vars/vault
    loop_control:
      loop_var: variable_file

  - name: Copy host file to Ansible Default Location
    copy:
      src: /root/Ansible/Atlassian/hosts
      dest: /etc/ansible/hosts
    
  - name: Create volume directories if they do not exist
    file:
      path: "{{ vol_dir }}/{{ tool_dir }}"
      state: directory
    loop:
      - bitbucket
      - crowd
      - jira
      - confluence
      - bamboo
      - mysql
    loop_control:
      loop_var: tool_dir
    
  - name: Make sure MySQL connector bin is in each volume (except jira)
    copy: 
      src: "{{ vol_dir }}/{{ mysql_bin_jar }}"
      dest: "{{ vol_dir }}/{{ vol }}/{{ mysql_bin_jar }}"
    loop:
      - bamboo
      - confluence
      - bitbucket
      - crowd
    loop_control:
      loop_var: vol

  - name: Move jira connector to it's volume
    copy:
      src: "{{ vol_dir }}/{{ mysql_jira_jar }}"
      dest: "{{ vol_dir }}/jira/{{ mysql_jira_jar }}"

  - name: Start Docker 
    service: 
      name: docker
      state: started

  - name: Create Containers
    include: "{{ containers }}"
    loop: 
      - roles/docker/main.yml
      - roles/mysql/main.yml
      - roles/jira/main.yml
      - roles/confluence/main.yml
      - roles/bamboo/main.yml
      - roles/bitbucket/main.yml
      - roles/crowd/main.yml
    loop_control:
      loop_var: containers
